### ISSUE TITLE
snap mission loading

### ISSUE THREAD

**Issue by gagalago** [snap-school/rsnap#11]
bug lors du chargement d'une mission dans snap dans une autre langue que l'anglais.

ce bug proviens surement soit du changement de langue qui ne regarde pas si un projet est en train d'etre chargé, soit du chargement de la mission qui n'informe pas snap qu'il y a un projet qui est en train de charger.

**Comment by gagalago** [comment]
j'ai plus le problème. et toi ?

**Comment by gaetanc** [comment]
seul les images ne charge pas
