### ISSUE TITLE
destroy/renew mission

### ISSUE THREAD

**Issue by gagalago** [snap-school/rsnap#25]
j'ai rajouté l'action(update) dans mon controlleur `InitializationProgramMissionsController`. il ne reste plus qu'a mettre un bouton qui va appeler l'adresse `/initialization_program_missions/:id` en PUT

ce que j'ai deja fait est dans la branche `reset-mission`

@gaetanc je te laisse terminer dans snap

**Comment by gaetanc** [comment]
voila ca ne marche pas encore on regardera ca ensemble en 5 min

**Comment by gaetanc** [comment]
done
