### ISSUE TITLE
le bloc when i receive en hat a disparu

### ISSUE THREAD

**Issue by gaetanc** [snap-school/rsnap#27]

**Comment by gagalago** [comment]
bizarre, je le vois dans les programme chat souris par exemple

**Comment by gaetanc** [comment]
la version de départ?

**Comment by gagalago** [comment]
j'en ai pris un au hazard qui était deja sur le serveur

Simon Claessens

2014-03-21 11:58 GMT+01:00 gaetanc notifications@github.com:

**Comment by gaetanc** [comment]
done
