### ISSUE TITLE
role snap

### ISSUE THREAD

**Issue by gagalago** [snap-school/rsnap#6]
c'est le bordel dans les roles utilisé dans snap.
- changer "0" et "1" par "student" et "teacher" pour avoir un code plus lisible.
- il faut reparcourir partout car les truc ne sont pas bien caché pour le "student" surtout les menu en haut

**Comment by gaetanc** [comment]
bon je n'ai pas compris les submodule je pense

**Comment by gaetanc** [comment]
je suis pas sur que c'est au bon endroit :s mais l'issue est dans rsnap donc je n'ai pas le choix je pense

**Comment by gaetanc** [comment]
bon ce n'était pas encore la bonne technique :(
